# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: Azure_East-West_no_NAT

# label should be a human readable label that conveys what this skillet will do
label: Azure Single VNet East-West traffic load balanced across 2 firewalls with out SNAT 

# description is a longer more informative version of a label
description: In this deployment East-West traffic across multiple APP segments would retain the original Source and Destination IP Address.

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  terraform_provider: azure
  collection:
    - Public Cloud
    - Deploy


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: sub_id
    description: Azure Subscription ID
    default: 
    type_hint: Refer Skillet guide
  - name: clnt_id
    description: Azure Client ID
    default:
    type_hint: Refer Skillet guide
  - name: clnt_sec
    description: Azure Client Secret Key
    default: 
    type_hint: Refer Skillet guide
  - name: tnt_id
    description: Azure Tenant id
    default: 
    type_hint: Refer Skillet guide
  - name: location
    description: Azure Region
    default: West India
    type_hint: Refer Skillet guide
  - name: bootstrap_sa1
    description: Azure Storage Account for Firewall-1 Bootstrap
    default: 
    type_hint: Refer Skillet guide
  - name: sa_key1
    description: Azure Storage Account key
    default: 
    type_hint: Refer Skillet guide  
  - name: file_share1
    description: Azure Storage Account File Share Name
    default: 
    type_hint: Refer Skillet guide  
  - name: bootstrap_sa2
    description: Azure Storage Account for Firewall-2 Bootstrap
    default: 
    type_hint: Refer Skillet guide
  - name: sa_key2
    description: Azure Storage Account key
    default: 
    type_hint: Refer Skillet guide  
  - name: file_share2
    description: Azure Storage Account File Share Name
    default: 
    type_hint: Refer Skillet guide  
  - name: mysourceip
    description: Public Ip address of the laptop used to access the Firewall and Host VM management Interface
    default: 
    type_hint: Refer Skillet guide
