variable "rg_name" {}
variable "location" {}
variable "vnet_name" {}
variable "cidr" {}
variable "ewlb_FE_address" {}
variable "mgmtSubnetName" {}
variable "mgmtSubnet" {}
variable "trustSubnetName" {}
variable "trustSubnet" {}
variable "app1SubnetName" {}
variable "app1Subnet" {}
variable "app2SubnetName" {}
variable "app2Subnet" {}
variable "instancetype" {}
variable "instanceSku" {}
variable "instanceVersion" {}
variable "bootstrap_sa1" {}
variable "sa_key1" {}
variable "file_share1" {}
variable "share_dir1" {}
variable "bootstrap_sa2" {}
variable "sa_key2" {}
variable "file_share2" {}
variable "share_dir2" {}
variable "adminUsername" {}
variable "adminPassword" {}
variable "bootstrap" {}
